version: 2
jobs:
  build:
    docker:
    - image: circleci/node:10.15.3
    steps:
    - add_ssh_keys:
        fingerprints:
        - "33:d0:0b:c6:e8:7a:93:fe:54:99:ff:57:c7:ce:4e:05"
    - checkout
    - run:
        name: Install
        command: npm install
    - run:
        name: Compile
        command: |
          npm run build
    - run:
        name: Test
        command: |
          npm test
          npm run test
    - run:
        name: Publish
        command: |
          git config --global user.email circleci@circleci.com
          git config --global user.name CircleCI
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
          git add 'package.json' 'package-lock.json' && (git diff-index --quiet HEAD || git commit -m 'Lock')
          if test "$CIRCLE_BRANCH" = "master"; then npm run cd; else git push origin $CIRCLE_BRANCH; fi
workflows:
  version: 2
  build_and_publish:
    jobs:
    - build